### ISSUE TITLE
Support for Redmi Earbuds 2c

### ISSUE THREAD

**Issue by chiragnahata** [d4rken-org/capod#1]
The app is not working. It is not detecting my Redmi earbuds 2c

**Comment by chiragnahata** [comment]
362b67c1-a3d6-4a8d-8fdb-1de73adcc9a1 my install id

**Comment by chiragnahata** [comment]
Done all these steps. But still it is not working

Chirag Nahata

**Comment by chiragnahata** [comment]
Now what to do ? Please help

**Comment by chiragnahata** [comment]
Log file

**Comment by chiragnahata** [comment]
Not resolved yet

**Comment by d4rken** [comment]
* Your logfile was not posted.
* If nothing shows after doing [this](https://github.com/d4rken/capod-public/issues/1#issuecomment-1112134423) then it's an issue with your device.
* I don't have Redmi earbuds 2c. I made this app to solve my own itches, it works perfectly with my Pixel 5 & AirPods Pro. I'm open for more, but if it's a totally different device, you'll have to step up and tell me how to decode it :slightly_smiling_face: .
