### ISSUE TITLE
Airpods Pro 2 issue with reactions 

### ISSUE THREAD

**Issue by nikhil-zappyhire** [d4rken-org/capod#105]
Hi,
Thanks for the awesome app. You are the only person/team who provide best app support for apple bluetooth devices.

But I'm facing some issue with the airpods pro 2 reactions in the CAPod app. I'm unable to use these feature like auto play/pause when whorn/remove the airpods from the ear. It doesn't pause/play the music/media. The experimental feature is working (popup window on connect).

I'm using the airpods pro I've brought from apple site with the engraving paired with samsung S21 Ultra 5G.

**Comment by d4rken** [comment]
This is unfortunately a bug in the AirPods 2 firmware, see #38.
