### ISSUE TITLE
Airpods Max are always detected as on ear

### ISSUE THREAD

**Issue by SavvySphynx** [d4rken-org/capod#106]
See title. I've been unable to find an app that can detect when my airpods leave my head, so it might not be doable.

**Comment by d4rken** [comment]
Not sure if it's possible, I don't own AirPods Max to text with. Does any of the raw data change (enable debug mode)?

**Comment by d4rken** [comment]
So
`0b00100011` (0x23)
vs
`0b00000011` (0x03)

**Comment by SavvySphynx** [comment]
Yes, it shows the same here 03 when worn, 23 when not. It changes several other values as well.

**Comment by d4rken** [comment]
Please report back after the next release :slightly_smiling_face:

**Comment by steam3d** [comment]
For me 22 when worn, 02 when not.
