### ISSUE TITLE
Airpods max ear detection reversed

### ISSUE THREAD

**Issue by bemoran** [d4rken-org/capod#115]
Hi all,

I installed the app today and have noticed that media plays when taking the airpods off, then stops when putting them back on. The app shows they are being worn when I have taken them off. I've tested it several times and it doesn't appear to be time related. 

Please let me know if you have any suggestions or need more info.

Thanks!

**Comment by d4rken** [comment]
Likely related to #106,  where  we fixed the detection based on this: 

> Yes, it shows the same here 03 when worn, 23 when not. It changes several other values as well.

Did we mixed up the states? Is it just reversed?

**Comment by steam3d** [comment]
For me 22 when worn, 02 when not.
