### ISSUE TITLE
CAPod Pro never find my airpods at first

### ISSUE THREAD

**Issue by ceifa** [d4rken-org/capod#137]
I always have to troubleshoot it to be found :/

Version: Latest on play store
Phone: Galaxy S9
Android: 10
Device: Airpods Pro

![Screenshot_20230603-154231_CAPod.jpg](https://github.com/d4rken-org/capod/assets/26205666/fe451de6-3f77-4a1e-b3e0-a990e65a4e19)

**Comment by d4rken** [comment]
Can you define "always"? When restarting CAPod? The phone? Your Pods?

The settings the troubleshooter ends up with are the default settings, so it's weird that this is required. Do the settings save? If you go into app settings, are the saved settings the same as the one in `#8` from the log?

**Comment by ceifa** [comment]
> Can you define "always"? When restarting CAPod? The phone? Your Pods?

When I open the airpods case. It shows a notification with "No device".

> The settings the troubleshooter ends up with are the default settings, so it's weird that this is required. Do the settings save? If you go into app settings, are the saved settings the same as the one in #8 from the log?

Yes, everything is disabled on settings. Scanner mode balanced and monitor mode when device is connected.

**Comment by d4rken** [comment]
I currently have no idea as to what could cause this.
Did you try just waiting a bit longer, maybe it just works, just takes longer until the data shows, and the troubleshooter is just a way to spend that time waiting.

**Comment by silence-ong** [comment]
I'm on a POCO F5 running MIUI Global 14.0.6
I'm also encountering this issue. I have Monitor mode set to "when device is connected" and I've also set my Airpods Pro at the device address. After connecting my Airpods, CAPods notification pops up saying no device.
I've to press troubleshoot to find my device, like ceifa's case, the settings always revert back to normal. And if I try reconnecting my Airpods afterwords, everything works fine.

I've read in Openpods that they currently have issues working with MIUI, maybe that is a cause?

**Comment by anderlopezsv** [comment]
Good afternoon. I have that problem too. I have a Samsung s21 FE, "No device" appears in the notifications and I can't find how to solve it.
![Screenshot_20231018_171619_Chrome](https://github.com/d4rken-org/capod/assets/148400574/706d146c-37e2-4f68-9669-98403ae9695c)

**Comment by anderlopezsv** [comment]
Good afternoon. I have that problem too. I have a Samsung s21 FE, "No device" appears in the notifications and I can't find how to solve it.

(I speak Spanish, sorry for any translation errors).

![Uploading Screenshot_20231018_171517_CAPod.jpg…]()

**Comment by anderlopezsv** [comment]
Good afternoon. I have that problem too. I have a Samsung s21 FE, "No device" appears in the notifications and I can't find how to solve it.

(I speak Spanish, sorry for any translation errors).

![Screenshot_20231018_171517_CAPod](https://github.com/d4rken-org/capod/assets/148400574/52bf5ec9-2495-4638-a809-1e5fcd4c5d50)
![Uploading Screenshot_20231018_171517_CAPod.jpg…]()

**Comment by d4rken** [comment]
Not much I can do, these are mostly ROM issues. Buggy Bluetooth Software Stacks.

Closing this in favor of #124
