### ISSUE TITLE
Why isn't this app available on Google Play anymore?

### ISSUE THREAD

**Issue by FeryET** [d4rken-org/capod#155]
Hi.

I wanted to install the app but couldn't find it in the store, and after clicking on the link in the README, I found out that your app page is deleted or suspended since Google Play is not showing it, could you elaborate why this has happened and whether you would like to return to google play after this?

**Comment by xiaoyaomeng** [comment]
很高兴收到您的邮件，看到后将立即回复~Thank you~

**Comment by d4rken** [comment]
Google terminated my whole developer account because my apps were **falsely** flagged as malware. I'm currently appealing the termination.

**Comment by d4rken** [comment]
Thank fully this bug was fixed yesterday. Only took 19 days :(.
