### ISSUE TITLE
Widget shows percentages with no device connected

### ISSUE THREAD

**Issue by maxpolzin** [d4rken-org/capod#163]
I cant upload a Screenshot atm, but the widget indicates a percentage even with no device connected. I'd expect it to show sth. like an x to indicate that no device is connected.

**Comment by d4rken** [comment]
It's the last known value. The idea was to view your battery without having to open the case or pick them up from your bag etc.

**Comment by maxpolzin** [comment]
Oh, I see. Thx for the clarification.
