### ISSUE TITLE
Issue with the your earbuds identification

### ISSUE THREAD

**Issue by MatchaChaCha** [d4rken-org/capod#168]
CApods has mistakenly taken someone else's airpods to be mine.

I'm on a train and the CAPods notification is displaying someone else's battery level. 

How can I specify which pair is mine?

**Comment by HK-DDboy** [comment]
这是一封自动回复邮件。已经收到您的来信，我会尽快回复。

**Comment by d4rken** [comment]
Set your AirPods type and if possible address in the settings, but sometimes it can't be prevented in crowded places because only apple has access to the unique identifier of the pods.
