### ISSUE TITLE
Device Airpods pro dissappeares from app by itself

### ISSUE THREAD

**Issue by slimshouki** [d4rken-org/capod#17]
App recognizes my airpods fine then after 10 seconds disappears from the app. I have to disconnect airpods pro and connects again but stays for 10 seconds then happens again. Attached debug report.[Debug log](https://drive.google.com/file/d/1PU-wnUaV1qxytt9f3IN8v3feNmH4tj6A/view?usp=drivesdk)

**Comment by d4rken** [comment]
> Build.Fingerprint: samsung/p3sxxx/p3s:12/SP1A.210812.016/G998BXXU5CVF2:user/release-keys
> BuildConfig.Versions: v1.3.13 (1031307) [dbba2e9] FOSS_RELEASE

The AirPods should show independent of whether they are connected. The displayed data comes from BLE broadcasts, which don't need a connection, that's only needed for audio. When AirPods are out of the case, or the case is open, they should constantly broadcast their status independent of whether a device is paired and connected.

The log shows that the system doesn't receive or forward any more broadcasts:

```
2022-08-02T04:57:26.038Z  V/CAP:Bluetooth:BleScanner: Flushing scan results.
2022-08-02T04:57:26.045Z  V/CAP:Bluetooth:BleScanner: onBatchScanResults(delay=1002ms, results=[])
```

You can try changing some of the Bluetooth setting in CAPod to see if it makes a difference.
