### ISSUE TITLE
Realme Buds Wireless 2S

### ISSUE THREAD

**Issue by meanindra** [d4rken-org/capod#19]
Can you add `realme Buds Wireless 2S`?
Here is some info about this device (linux desktop screenshot)

![Screenshot from 2022-08-05 14-29-29](https://user-images.githubusercontent.com/36324543/183042364-2b7e6599-142b-46a9-84be-fc35af31cd8e.png)  

If this is not helpful, can you tell me how you or other extracted Bluetooth data from other devices?
Thanks

**Comment by d4rken** [comment]
AirPod data is transmitted through Bluetooth low energy advertisement .

In CAPod enable "unfiltered BLE data" and see if you can pick out your headphones, if they are visible, figure out what the raw data means 🙂

**Comment by meanindra** [comment]
My headphones is not visible. Closing this issue.
