### ISSUE TITLE
Notification shows wrong text when minimized

### ISSUE THREAD

**Issue by heschy2** [d4rken-org/capod#198]
The Phone is connected to my Airpods Pro, so CAPod creates a persitent notification (see image):
![signal-2024-03-15-14-15-02-556.jpg](https://github.com/d4rken-org/capod/assets/105609148/22f6550c-c832-4215-9880-ceeae778b663)

However, the notification is minimized by default (which is okay and may be my fault). Thats not the problem, the problem is that the Minimized nitification says there is no device connected:
![signal-2024-03-15-14-15-02-556-1.jpg](https://github.com/d4rken-org/capod/assets/105609148/072293a2-b66b-4a71-9566-90f5b8ad86f2)

Seems to be a bug that (I assume) can be fixed easily, right (not meant to be a reproach I am just curious)?

**Comment by d4rken** [comment]
What phone and ROM is that? Can't reproduce this on my device.

**Comment by heschy2** [comment]
Fairphone 5 (FP5) with the newest Version of /e/OS

**Comment by hf02** [comment]
Also getting this on a Galaxy S23 running One UI 6.1

**Comment by TipzRickyCheung** [comment]
Reproduced on LineageOS 19.1 with OPPO A57
