### ISSUE TITLE
Crash on open, galaxy s23

### ISSUE THREAD

**Issue by FistashkaWhite** [d4rken-org/capod#214]
I have an s23 and the app crashes as soon as its opened. I've tried using both, the build from github as well as play store.

There are no error messages, just "CAPod keeps stopping". 

Is there something I forgot to do? Does anyone else have the same issue?

** So after installing the v2.11 it seems to be working without crashes, but the autopause (which im after) doesnt seem to be working, the app always tags the airpods as "In ear". I am using Airpods Pro 2 btw. Just to eliminate any obvious issues, the autopause works flawlessly on a macbook

**Comment by d4rken** [comment]
It only crashes on v2.13?

**Comment by FistashkaWhite** [comment]
v2.13 and v2.12 both crash
