### ISSUE TITLE
Support for AirPods 4 (non-ANC) 

### ISSUE THREAD

**Issue by ASOwnerYT** [d4rken-org/capod#225]
I recently got genuine Airpods Generation 4 (non-ANC) and will be happy to provide any data needed to get this working. Currently they show up as "Unknown device".  I've attached the debug logs without device filter, let me know if there's anything else you need: [capod_logfile_1727043688286.log.zip](https://github.com/user-attachments/files/17091474/capod_logfile_1727043688286.log.zip)

**Comment by znbaboy** [comment]
I have the ANC version. ping me if you need anything also

**Comment by ASOwnerYT** [comment]
Thanks for adding this so quickly! All seems to work well
