### ISSUE TITLE
Airpods Gen 4 not detected 

### ISSUE THREAD

**Issue by GarethW22** [d4rken-org/capod#232]
![Screenshot_20240927-192710](https://github.com/user-attachments/assets/dbbe23a0-a041-4a28-accf-8741634cff8e)

Received the following message when attempting to detect my Airpods 4 (with ANC)

Raw data 76: 07 19 01 1B 20 2B A9 8F 12 00 05 73 BD 3B 32 F6 A4 D1 55 B5 D2 AB CD 67 C3 66 CB

**Comment by ASOwnerYT** [comment]
What version are you using? Airpods 4 work for me in version v2.15.0-rc0 (from Github releases)

**Comment by GarethW22** [comment]
Thanks, looks like the version I grabbed from F-droid was somehow the old
version. Thanks for the speedy response - confirmed the latest version is
working fine.
