### ISSUE TITLE
Notifications not working

### ISSUE THREAD

**Issue by GrantSavill** [d4rken-org/capod#29]
Notifications are not working with the latest version (2.1.0) on Android 13.

Toggle shows as greyed out:

[Screenshot_20220919-204754.png](https://user-images.githubusercontent.com/20668755/191103264-420040f4-0051-4754-b6d2-ac0fc7d26626.png)

**Comment by d4rken** [comment]
Did it not ask you to grant permission on first launch?

**Comment by GrantSavill** [comment]
No it didn't. Tried reinstalling and clearing storage too

**Comment by d4rken** [comment]
Should be fixed in v2.1.1-rc0 which will be building soon. Thanks for the feedback :beers:
