### ISSUE TITLE
Permanent wakelock prevents sleep, idle battery drain high

### ISSUE THREAD

**Issue by AeliusSaionji** [d4rken-org/capod#41]
![Screenshot_20221026-090003](https://user-images.githubusercontent.com/4342746/198032719-dd6a27a6-ae36-4e97-b6a5-3268b6cb9cee.png)

This is with scanner mode set to "low power".
I try to set monitor mode to "when connected", but it consistently reverts to "always".

**Comment by d4rken** [comment]
High battery consumption is expected with the "Always" mode, as Bluetooth & CPU can't go to sleep.

If you can't change it, then you have another option active that needs this, e.g. "Auto connect".

**Comment by AeliusSaionji** [comment]
I do not. I saw the note that auto connect overrides your scanner selection, and made sure to turn it off.

One way or another, "always" gets flipped on and I can't make it stop.

**Comment by AeliusSaionji** [comment]
https://user-images.githubusercontent.com/4342746/198141262-e4e83d55-b601-4e9a-be77-a514a729cad7.mp4

**Comment by d4rken** [comment]
Uh :thinking: yeah that's a bug.

**Comment by d4rken** [comment]
Thanks :heart: , fixed in next update.
