### ISSUE TITLE
New functionality 

### ISSUE THREAD

**Issue by jnj770** [d4rken-org/capod#45]
Can you pkease add the functionality of the notification widget that it goes off when the airpods are disconnected.

**Comment by d4rken** [comment]
Can you further describe how this would help you?

**Comment by jnj770** [comment]
It's annoying to see a notification that we can't remove and also its not useful while no device is connected so its useless.

**Comment by d4rken** [comment]
The notification is visible if you have set monitor mode to "always".
To keep a service running and "always" monitor, we need a notification.
So this is working as expected.

Also see #28 which might be what you want, but isn't implemented yet.
