### ISSUE TITLE
Airpods Pro 2-auto pause

### ISSUE THREAD

**Issue by xSKUUUx** [d4rken-org/capod#57]
Hello, when i when I take off one of my headphones, the music does not pause

**Comment by Mario-119** [comment]
Can confirm the same issue, auto play/pause is broken. When I take an airpod out, it actually continues playing it even when both of the pods are removed from my ears

**Comment by Neykuratick** [comment]
doesn't work for me too

**Comment by d4rken** [comment]
Dup of #38
