### ISSUE TITLE
Airpods Pro Gen 2 Support Help

### ISSUE THREAD

**Issue by easyax** [d4rken-org/capod#59]
I just bought airpods pro 2nd generation and I am an android user. I did not fully understand the application.  It says in ear even though I take off the earphones. And when the headphones are connected, the popup does not appear.
[Screen Record ](https://drive.google.com/file/d/1eOqr38dC1_wm4s0AfiV4NjuipxghZciI/view?usp=drivesdk) 
[Screenshot_20221204-204254_CAPod](https://user-images.githubusercontent.com/59334399/205507332-5c095d58-55aa-4e1d-8e09-1849ab0c6302.png)
[Screenshot_20221204-204206_CAPod](https://user-images.githubusercontent.com/59334399/205507731-b871e1f2-a0b9-4493-862d-dd3536e937ff.png)

**Comment by d4rken** [comment]
The in-ear detection is not working right for Airpods Pro 2, likely a bug in the firmware (see #38).

For the pop-up to work, do you have your device type and address selected in settings?

**Comment by easyax** [comment]
After resetting and reconnecting airpods pop up solved. Is there nothing I can do to use spatial sound?

**Comment by d4rken** [comment]
> Is there nothing I can do to use spatial sound?

Apple has not made this accessible :frowning_face:
