### ISSUE TITLE
Matching AirPod icons instead of generic earbud icons

### ISSUE THREAD

**Issue by christoschronopoulos** [d4rken-org/capod#62]
Thank you for your efforts! I know it is trivial and solely aesthetic, but I would like to ask if it is possible to edit the notification icons to the actual images of the AiPods (e.g., Pro 2) and Case.

**Comment by d4rken** [comment]
Yes it's possible, can you can design a good looking set?

**Comment by christoschronopoulos** [comment]
I can definitely do that! Now that it's Xmas holidays I will have some free time! 
Only, please let me know what are the filetype and image size requirements.

**Comment by d4rken** [comment]
Can you show me a screenshot of which icons you would like to replace, to make sure we are talking about the right ones :grin:

**Comment by christoschronopoulos** [comment]
Sure, please see the screenshots below (icons marked in red)! I am primarily talking about the notification icons, but if we could also change the ones in the widget would be great!
![Screenshot_2022-12-22-16-48-41-390_com miui home~2](https://user-images.githubusercontent.com/12989098/209172270-7846e17c-2f71-407c-8754-4a5620cf8e4a.jpg)
![Screenshot_2022-12-22-16-47-41-408_com miui home~2](https://user-images.githubusercontent.com/12989098/209172324-bc33d312-dd96-4333-98cf-03fd7737d60b.jpg)

**Comment by christoschronopoulos** [comment]
I would very much like to replace those icons with actual images of the AirPods Pro 2. Something like that 
![MQD83DN-A-ETUI_4wnIVb79I61eyEZSJ7XdI](https://user-images.githubusercontent.com/12989098/209173901-70ed4f9a-75ba-4869-a15e-cd26dbd1eec4.jpg)
![apple-airpods-pro-2nd-gen-2022-true-wireless-horetelefoner](https://user-images.githubusercontent.com/12989098/209174021-ea9fdebc-9b90-4f8d-9e66-1417ad33c19c.jpg)

**Comment by d4rken** [comment]
Most of the current icons are from https://materialdesignicons.com/
That's also the style i use all over the app, but I'm not against using less "icon-like" images if it looks good :smiley:.

A vector graphic would be best, i.e. a SVG file. This is the SVG of the current icon:
https://github.com/d4rken-org/capod/blob/main/app-common/src/main/res/drawable/ic_airpod_left_24.xml

A PNG is also possible, needs to be least 48px*48px.
Transparent background.

> I would very much like to replace those icons with actual images of the AirPods Pro 2. Something like that

Just make sure no Apple lawyers descend on us like banshees.

> but if we could also change the ones in the widget would be great!

We can, if we get a full set we can use to display the specific icon everywhere, we'd need these 4 types of image:
![Screenshot from 2022-12-22 17-08-51](https://user-images.githubusercontent.com/1439229/209175742-61bce802-a67f-42d3-bc40-0c56cf31f186.png)![Screenshot from 2022-12-22 17-08-47](https://user-images.githubusercontent.com/1439229/209175746-78e25c71-e08b-4b97-b1f0-ad509ffcdc55.png)
![Screenshot from 2022-12-22 17-08-40](https://user-images.githubusercontent.com/1439229/209175751-1972aecf-947f-45fe-8b97-e32665ed836f.png)![Screenshot from 2022-12-22 17-08-36](https://user-images.githubusercontent.com/1439229/209175754-968172c0-ac61-447d-8ee9-ef84d1602845.png)

**Comment by christoschronopoulos** [comment]
> Just make sure no Apple lawyers descend on us like banshees.

That's a valid point! Not sure though if using them as 45px icons in an open source app would be an infringement. :/

> A vector graphic would be best, i.e. a SVG file. This is the SVG of the current icon: https://github.com/d4rken-org/capod/blob/main/app-common/src/main/res/drawable/ic_airpod_left_24.xml
>
> A PNG is also possible, needs to be least 48px*48px. Transparent background.

In the attached zip I have included both SVG and PNG images at 500px. Regarding the tint, I don't know how the white icons would look in Dark/Light themes. Could you try and share a screenshot or two?

[AirPods Pro 2.zip](https://github.com/d4rken-org/capod/files/10290043/AirPods.Pro.2.zip)

**Comment by d4rken** [comment]
With tintmode multiply
![Screenshot from 2022-12-23 08-44-06](https://user-images.githubusercontent.com/1439229/209294321-986bb2b7-7cfb-4ad5-8066-d6a55af3e153.png)![Screenshot from 2022-12-23 08-46-35](https://user-images.githubusercontent.com/1439229/209294787-31804396-25ae-4751-9c48-0a1f07640265.png)

Tintmode `src_atop`

![Screenshot from 2022-12-23 08-45-42](https://user-images.githubusercontent.com/1439229/209294937-dd47841b-d8d8-4cbe-ac63-ae326a5fbec0.png)![Screenshot from 2022-12-23 08-45-20](https://user-images.githubusercontent.com/1439229/209294940-70feef3a-8bdd-4819-b396-bf446a3292b4.png)

**Comment by d4rken** [comment]
Building a new release right now, see how you like it.
I went with tintmode multiply.

btw, the SVGs are not "real" they just contain the png image in binary form.

**Comment by christoschronopoulos** [comment]
Thanks for your effort!!! Hmmm, tbh I don't like how they look. Maybe it is due to the low quality of the icons that I sent when their size is reduced. Good to know about the SVGs. I exported them in Photoshop, so I didn't expect that. I need to find another way to create them, maybe GIMP will do the job. 

I don't know what "tintmode multiply" is. Could you please explain?

**Comment by d4rken** [comment]
> I don't know what "tintmode multiply" is. Could you please explain?

Just different ways to apply the tint color, you can see the difference in the examples above.
![Screenshot from 2022-12-23 10-37-49](https://user-images.githubusercontent.com/1439229/209311685-9e42216d-210f-4cfb-9fb8-b03506df2a35.png)![Screenshot from 2022-12-23 10-37-43](https://user-images.githubusercontent.com/1439229/209311688-0e9cd0cd-c095-4106-88ce-128c0fd7b774.png)

**Comment by christoschronopoulos** [comment]
[AirPods Pro 2_svg.zip](https://github.com/d4rken-org/capod/files/10297189/AirPods.Pro.2_svg.zip)

I worked a little bit on the SVG icons with Inkscape. I think they are "true" SVGs now, and better in terms of quality. How can I get a new release to try it out? Will it affect the Pro version that I have?

**Comment by d4rken** [comment]
> How can I get a new release to try it out?

The previous icons are in the latest release, to get these newer ones, you could copy the current icons in and build a new version from sources.

> Will it affect the Pro version that I have?

You will have to uninstall that but can later reinstall.

I don't see a difference to the previous icons :thinking: The left/right icon could need some extra padding/margins.

![Screenshot from 2022-12-24 10-49-50](https://user-images.githubusercontent.com/1439229/209430627-fd876b66-ed94-4b06-b100-19c2c7d8f755.png)![Screenshot from 2022-12-24 10-47-40](https://user-images.githubusercontent.com/1439229/209430630-b977c3d2-39fe-4557-b875-573fa42527a5.png)

**Comment by d4rken** [comment]
The real vector graphics are too complex, Android Studio warns about performance issuse:
>  Very long vector path (12290 characters), which is bad for performance. Considering reducing precision, removing minor details or rasterizing vector.

There are also some artifacts:
![Screenshot from 2022-12-24 10-54-47](https://user-images.githubusercontent.com/1439229/209430790-e822bc12-d917-462e-a4a8-90d9c2bc0491.png)

**Comment by d4rken** [comment]
I've added some padding. Looks good imho.
![Screenshot from 2022-12-24 11-14-47](https://user-images.githubusercontent.com/1439229/209431530-5228b16a-d18b-4048-af61-47f374268f85.png)
![Screenshot from 2022-12-24 11-14-21](https://user-images.githubusercontent.com/1439229/209431531-852be49a-6761-4f1b-8927-c0784289de68.png)![Screenshot from 2022-12-24 11-14-08](https://user-images.githubusercontent.com/1439229/209431532-156b47ef-7520-430a-8197-931868f0b4de.png)

Noticed a bug in the current release, the new icons are only used for AirPod Pro1 not the Pro2.

**Comment by christoschronopoulos** [comment]
> I've added some padding. Looks good imho. ![Screenshot from 2022-12-24 11-14-47](https://user-images.githubusercontent.com/1439229/209431530-5228b16a-d18b-4048-af61-47f374268f85.png) ![Screenshot from 2022-12-24 11-14-21](https://user-images.githubusercontent.com/1439229/209431531-852be49a-6761-4f1b-8927-c0784289de68.png)![Screenshot from 2022-12-24 11-14-08](https://user-images.githubusercontent.com/1439229/209431532-156b47ef-7520-430a-8197-931868f0b4de.png)
> 
> Noticed a bug in the current release, the new icons are only used for AirPod Pro1 not the Pro2.

Looks good indeed! I will check the latest release with my AirPods Pro 2.

**Comment by christoschronopoulos** [comment]
@d4rken is there any way to prevent the tint color from being applied to the icons? I mean, I would like to test the icons appearing as white (original color) always.

**Comment by d4rken** [comment]
> is there any way to prevent the tint color from being applied to the icons? I mean, I would like to test the icons appearing as white (original color) always.

Not in the build APK, you'd have to edit the code and install from source.

![Screenshot from 2022-12-24 13-52-14](https://user-images.githubusercontent.com/1439229/209437086-1d8cd843-f685-4135-ab73-acb476cf2726.png)![Screenshot from 2022-12-24 13-52-02](https://user-images.githubusercontent.com/1439229/209437087-b1083b42-d240-4178-bad2-ec800fd01d3b.png)

Without tinting the contrast is low on bright backgrounds

**Comment by christoschronopoulos** [comment]
I see your point, but tbh I prefer the white even on light-color backgrounds as I see it on your screenshot. It looks really good!

**Comment by d4rken** [comment]
For in-app this could be viable as there we fixed the theme colors, but the widget and notifications make use of Android's dynamic theming. So the colors match what ever the user has picked (fixed, custom or based on wallpaper).

Tough :thinking: 

I'm tending towards keeping the tinting, the custom icons are already an improvement over the previous ones.

**Comment by christoschronopoulos** [comment]
Hmmm, since the new icons look good in your screenshot with (almost) white background, I don't see why they wouldn't look as good with other user-selected light-color themes. But anyway.

**Comment by d4rken** [comment]
Maybe if we have icons like these for all devices?
I don't want to add extra code to turn on/off depending on which icon it is.

Let's not over-complicate this. :beers:

**Comment by christoschronopoulos** [comment]
Makes total sense. In the following days I will try to create proper SVGs for the major AirPods versions as per your feedback, and you can take it from there of you think is feasible.
