### ISSUE TITLE
Automatic play/pause not working (AirPods 1st gen)

### ISSUE THREAD

**Issue by ghost** [d4rken-org/capod#66]
Ear detection with automatic play/pause is not working on AirPods 1st gen.
Firmware version : 6.8.8
All options are enabled and all requested permissions granted

When removing an earphone, the music does not stop. You must remove both earphones to stop it

**Comment by d4rken** [comment]
Does the EAR state show quickly/correctly in the UI?

**Comment by FilidorZeleniy** [comment]
> Does the EAR state show quickly/correctly in the UI?

Yes
