### ISSUE TITLE
AirPod Pro 2 actions problems

### ISSUE THREAD

**Issue by p3dr01978** [d4rken-org/capod#99]
HI , my airpod pro 2 

None of the pro actions are recognised at all (auto pause etc...)

My airpod firmware is 5b58 model number a2698

**Comment by d4rken** [comment]
What code do you get? The long hex number at the bottom of the card. You might have to enable debug mode in CAPod.

Could be fake AirPods 2?

**Comment by p3dr01978** [comment]
The discovery issue  I mentioned at the beginning was due to fake air pod 2 (stupid me, but I fixed it few minute after I wrote here ), for the actions like pause removing one arpod, etc... no solution and they are not working. My ID  (see the attached image) 
![ID](https://user-images.githubusercontent.com/74537607/218275625-124c2abd-cb1d-435e-8c31-48ae1e5dd713.jpeg)

**Comment by d4rken** [comment]
> The discovery issue I mentioned at the beginning was due to fake air pod 2 (stupid me, but I fixed it few minute after I wrote here ), for the actions like pause removing one arpod, etc... no solution and they are not working. 

This may be due to an Apple firmware bug, see: #38

**Comment by p3dr01978** [comment]
thanks let's wait a new firmware

**Comment by Adithyan007hack** [comment]
> The discovery issue I mentioned at the beginning was due to fake air pod 2 (stupid me, but I fixed it few minute after I wrote here ), for the actions like pause removing one arpod, etc... no solution and they are not working. My ID (see the attached image) ![ID](https://user-images.githubusercontent.com/74537607/218275625-124c2abd-cb1d-435e-8c31-48ae1e5dd713.jpeg)

Did succeeded in connecting fake airpods??
